"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);
  };

  return (
    <html lang="fa" dir="rtl">
      <body className={inter.className}>
        <div className="bg-white relative shadow-md py-2">
          <div className="w-full h-16 container  flex items-center justify-between">
            <div className=" w-1/3 flex items-center">
              <div className="w-16 h-16">
                <img className="w-full h-full" src="/images/logos.png" />
              </div>
              <p>مدرسه منتخب دانش آموزان</p>
            </div>

            <div className=" text-center w-1/3">
              <p>صفحه اصلی </p>
            </div>

            <div className=" flex gap-x-8 justify-end w-1/3">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="gray"
                class="w-6 h-6"
              >
                <path d="M5.85 3.5a.75.75 0 00-1.117-1 9.719 9.719 0 00-2.348 4.876.75.75 0 001.479.248A8.219 8.219 0 015.85 3.5zM19.267 2.5a.75.75 0 10-1.118 1 8.22 8.22 0 011.987 4.124.75.75 0 001.48-.248A9.72 9.72 0 0019.266 2.5z" />
                <path
                  fill-rule="evenodd"
                  d="M12 2.25A6.75 6.75 0 005.25 9v.75a8.217 8.217 0 01-2.119 5.52.75.75 0 00.298 1.206c1.544.57 3.16.99 4.831 1.243a3.75 3.75 0 107.48 0 24.583 24.583 0 004.83-1.244.75.75 0 00.298-1.205 8.217 8.217 0 01-2.118-5.52V9A6.75 6.75 0 0012 2.25zM9.75 18c0-.034 0-.067.002-.1a25.05 25.05 0 004.496 0l.002.1a2.25 2.25 0 11-4.5 0z"
                  clip-rule="evenodd"
                />
              </svg>
              {/* menu icon */}
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                stroke-width="1.5"
                stroke="gray"
                class="w-6 h-6 cursor-pointer  hover:stroke-black"
                onClick={toggleMenu}
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                />
              </svg>

              {isMenuOpen && (
                <div
                  className="fixed top-0 left-0 w-full h-full bg-black opacity-60 z-40"
                  onClick={toggleMenu}
                />
              )}

              {isMenuOpen && (
                <div className="absolute popup-menu overflow-x-auto top-[18rem] h-[400px] rounded-md left-60 w-[300px] transform -translate-x-1/2 -translate-y-1/2 bg-white  z-50">
                  <div className="rounded-t-[6px]  relative h-[120px] w-full bg-gradient-to-r from-white to-black">
                    <img
                      className="rounded-t-[6px] h-full w-full "
                      src="/images/drop.jpg"
                    />
                    <div className="absolute z-20 top-[50%] translate-y-[-50%] right-[50%] translate-x-[60%]">
                      <p className="whitespace-nowrap text-white">mohammad farhadi</p>
                      <p className="text-white">(معلم)</p>
                    </div>
                    <div className="absolute  inset-0 bg-blue-600 opacity-70"></div>

                  </div>
                  <div className="p-8 px-4 ">
                    <div className="mb-4 flex items-center gap-x-2">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-6 h-6"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
                        />
                      </svg>

                      <p>اخبار</p>
                    </div>

                    <div className="mb-4 flex items-center gap-x-2">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-6 h-6"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
                        />
                      </svg>

                      <p>بانک سوالات</p>
                    </div>

                    <div className="mb-4 flex items-center gap-x-2">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-6 h-6"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
                        />
                      </svg>

                      <p>اموزش انلاین  </p>
                    </div>


                    <div className="mb-4 flex items-center gap-x-2">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        class="w-6 h-6"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z"
                        />
                      </svg>

                      <p>خروج</p>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
