import type { Metadata } from "next";
import "../../src/app/globals.css";
import { Inter } from "next/font/google";
import {Figtree} from "next/font/google";
import localFont from "next/font/local"


// const figtree  = Figtree({
//   display:"swap",
//   subsets:["latin"],
//   weight:["300","400","500","600","700","800","900"],
//   variable:"--font-figtree"
// })

// const yekanbakh = localFont({
//   src:[
//     {
//       path:"https://assets.edu-world.ir/fonts/iransans/v8/Webfonts/fonts/woff/IRANSansX-Thin.woff",
//       weight:"100",
//       style:"normal"

//     },
    
//   ],
//   variable:"--font-yekanbakh"

// })



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa-IR" dir="rtl" >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
